# This file lists the dependencies needed to build and test all of
# veerer.
# Create a Conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: veerer-build
channels:
  - conda-forge
dependencies:
  - cython
  - pytest
  - pytest-xdist
  - ipywidgets
  - scipy
  - matplotlib-base
  - gap-defaults
  - sympy
  - sagemath-db-conway-polynomials
  - sagelib >=9.3
  # some of the tests rely on ipywidgets which is not required by sagelib
  - ipywidgets
  - pyeantic >=1  # optional: pyeantic
  - pyintervalxt >=3,<4  # optional: pyintervalxt
  - pyflatsurf >=3.10.1 # optional: pyflatsurf
  # Work around https://github.com/conda-forge/pynormaliz-feedstock/issues/10 by pinning normaliz and pynormaliz
  - pynormaliz 2.19  # optional: pynormaliz
  - normaliz 3.10.2  # optional: pynormaliz
  - sphinx >=4.2.0,<6  # optional: doc
  - pip
  - surface-dynamics  # optional: surface_dynamics
  - pip:
    - linkchecker  # optional: doc
    - sphinx_rtd_theme  # optional: doc
    - flipper  # optional: flipper
    # Use a version including https://github.com/flatsurf/sage-flatsurf/pull/269
    - git+https://github.com/flatsurf/sage-flatsurf.git  # optional: sage_flatsurf
