name: Documentation
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-manual:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest" }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: install veerer
        shell: bash -l {0}
        run: |
          pip install --no-index .
      - name: fix permissions
        shell: bash -l {0}
        run: |
          # Strangely, the linkchecker modules are installed writable and linkchecker then refuses to load them.
          chmod -R a-w `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
      - name: build documentation
        shell: bash -l {0}
        run: |
          sphinx-build -b html -n doc/source html/veerer --color -a -E -W
          touch html/veerer/.nojekyll
      - name: detect broken links
        shell: bash -l {0}
        run: |
          python -m http.server 8880 --directory html &
          sleep 1
          # We ignore _modules since sphinx puts all modules in the module
          # overview but does not generate pages for .pyx modules.
          linkchecker --check-extern --ignore-url=_modules/ http://localhost:8880
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: html/veerer
          TARGET_FOLDER: docs/
        if: ${{ github.event_name == 'push' }}
