name: Code Lint
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest" }
      - name: install codespell
        shell: bash -l {0}
        run: |
          mamba install -y codespell
      - name: run codespell
        shell: bash -l {0}
        run: |
          codespell `git ls-files`
