name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - optionals: "sage"
            sagelib: "9.3"
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest" }
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba install -n test sagelib=${{ matrix.sagelib }}
          echo "sagelib ==${{ matrix.sagelib }}" >> $CONDA_PREFIX/conda-meta/pinned

          while read; do
            optional=$(echo "$REPLY" | grep -o '# optional: [^ ]*' | awk '{ print $3; }') || true
            (test "$optional" == '' || (echo "${{ matrix.optionals }}" | grep -E '\b'"$optional"'\b') > /dev/null) && echo "$REPLY" || true
          done < environment.yml > environment.test.yml

          mamba env update --quiet -n test -f environment.test.yml

          conda list
      - name: Install veerer
        shell: bash -l {0}
        run: |
          pip install --verbose --no-index .
          # Show message about cppyy regenerating pre-compiled headers so it does not show during the tests
          python -c 'import cppyy' || true
      - name: Run SageMath doctests
        shell: bash -l {0}
        run: |
          sage -tp --force-lib --long --optional=${{ matrix.optionals }} veerer doc
      - name: Run pytest
        shell: bash -l {0}
        working-directory: tests
        run: pytest -n auto
      - name: Show logs
        run: grep "" /dev/null `find -name '*.log'` || true
        if: ${{ always() }}

env:
  MAKEFLAGS: -j2
  SAGE_NUM_THREADS: 2
